<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>Microsoft.ML.NugetPackageVersionUpdater.Program</StartupObject>
    <RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFrameworks />
  </PropertyGroup>

</Project>
